config/routes.rb
Rails.application.routes.draw do

  resources :payments, only: [:index, :new, :create]

  get 'auth/failure', to: redirect('/')
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resources :products, only: [:index]
  resource :cart, only: [:show]
  get 'carts/show'
  get 'emptycart' => 'carts#emptycart'
  resources :order_items, only: [:create, :update, :destroy]
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'

  get 'products/index'
  root to: "products#index"

end

app/models/customer.rb
class Customer < User
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  belongs_to :user
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  require "active_merchant/billing/rails"

  attr_accessor :card_security_code
  attr_accessor :credit_card_number
  attr_accessor :expiration_month
  attr_accessor :expiration_year

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :card_security_code, presence: true
  validates :credit_card_number, presence: true
  validates :expiration_month, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 12 }
  validates :expiration_year, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }

  validate :valid_card

  def credit_card
    ActiveMerchant::Billing::CreditCard.new(
      number:              credit_card_number,
      verification_value:  card_security_code,
      month:               expiration_month,
      year:                expiration_year,
      first_name:          first_name,
      last_name:           last_name
    )
  end

  def valid_card
    if !credit_card.valid?
      errors.add(:base, "The credit card information you provided is not valid.  Please double check the information you provided and then try again.")
      false
    else
      true
    end
  end

  def process
    if valid_card
      response = GATEWAY.authorize(amount * 100, credit_card)
      if response.success?
        transaction = GATEWAY.capture(amount * 100, response.authorization)
        if !transaction.success?
          errors.add(:base, "The credit card you provided was declined.  Please double check your information and try again.") and return
          false
        end
        update_columns({authorization_code: transaction.authorization, success: true})
        true
      else
        errors.add(:base, "The credit card you provided was declined.  Please double check your information and try again.") and return
        false
      end
    end
  end
end

app/models/pie.rb
class Pie < Product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items

  default_scope { where(active: true) }
end

app/models/salad.rb
class Salad < Product
end

app/models/side.rb
class Side < Product
end

app/models/sub.rb
class Sub < Product
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.type = "Customer"
      user.save!
    end
  end
end

app/models/wing.rb
class Wing < Product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :current_order, :logged_in?

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def allow_user
    redirect_to root_path unless logged_in?
  end

  def logged_in?
    session[:user_id] && current_user.present?
  end

  def redirect_unless_logged_in
    redirect_to '/' unless logged_in?
  end

  def redirect_if_already_logged_in
    redirect_to '/' if logged_in?
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end

  def emptycart
    current_order.order_items.each do |item|
      item.delete
    end
    redirect_to '/carts/show'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @payments = Payment.all
  end

  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new(payment_params)

    if @payment.save
      if @payment.process
        redirect_to payments_path, notice: "The user has been successfully charged." and return
      end
    end
    render 'new'
  end

private
  def payment_params
    params.require(:payment).permit(:first_name, :last_name, :credit_card_number, :expiration_month, :expiration_year, :card_security_code, :amount)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @salads = Salad.all
    @sides = Side.all
    @wings = Wing.all
    @subs = Sub.all
    @pizzas = Pie.all
    
    @order_item = current_order.order_items.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    @orders = current_user.orders
  end

  def edit
    @user = User.find(params[:id])
    redirect_unless_editing_or_deleting_own(@user)
  end

  def update
    @user = User.find(params[:id])
    redirect_unless_editing_or_deleting_own(@user)

    @user.assign_attributes(user_params)

    if @user.save
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    redirect_unless_editing_or_deleting_own(@user)

    @user.destroy
    redirect '/users'
  end

  private
  def user_params
    params.require(:user).permit(:name,
                                 :type,
                                 :email,
                                 :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
  def months
    (1..12).collect{|n| ["#{n} - #{Date::MONTHNAMES[n]}", n]}
  end

  def years
    (Time.now.year..Time.now.year+15)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/payments/create.html.erb
<h1>Payments#create</h1>
<p>Find me in app/views/payments/create.html.erb</p>

app/views/payments/index.html.erb
<h1>Payment Attempts</h1>
<div class="well">
<%= link_to "New Payment", new_payment_path, class: "btn btn-primary" %>
</div>
<% if !flash[:notice].blank? %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>
<table class="table table-bordered table-striped">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Last 4</th>
    <th>Amount</th>
    <th>Succeeded?</th>
    <th>Authorization Code</th>
  </tr>
  <% if @payments.size > 0 %>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.first_name %></td>
        <td><%= payment.last_name %></td>
        <td><%= payment.last4 %></td>
        <td><%= number_to_currency payment.amount %></td>
        <td><%= payment.success == true ? "Yes" : "No" %></td>
        <td><%= payment.authorization_code %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="5">No payments have been attempted.</td>
    </tr>
  <% end %>
</table>

app/views/payments/new.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <h1>New Payment</h1>

    <% if @payment.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @payment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="well">
      <%= form_for @payment do |f| %>
        <div class="form-group">
          <%= f.label :first_name, class: "control-label" %>
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :last_name, class: "control-label" %>
          <%= f.text_field :last_name,class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :credit_card_number, class: "control-label" %>
          <%= f.text_field :credit_card_number, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :expiration_month, class: "control-label" %>
          <%= f.select :expiration_month, months, {}, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :expiration_year, class: "control-label" %>
          <%= f.select :expiration_year, years, {}, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :card_security_code, class: "control-label" %>
          <%= f.text_field :card_security_code, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :amount, class: "control-label" %>
          <%= f.number_field :amount, class: "form-control", step: "0.01" %>
        </div>
        <div class="form-group">
          <%= f.submit "Charge Credit Card", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>